-- Migration 016: Produktnamen-Vorschlagsliste
-- Ergänzt bekannte Produktnamen als Autocomplete-Vorschläge

-- ============================================
-- SCHRITT 1: Tabelle für Produktnamen-Vorschläge
-- ============================================
CREATE TABLE IF NOT EXISTS product_name_suggestions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_pns_name (name)
) ENGINE=InnoDB;

-- ============================================
-- SCHRITT 2: Bekannte Produktnamen einfügen
-- Diese Liste enthält gängige Interventions-Materialien
-- Duplikate mit bereits in products existierenden Namen werden übersprungen
-- ============================================
INSERT IGNORE INTO product_name_suggestions (name) VALUES
('Abre'),
('Absolute Pro'),
('Access Wires'),
('Adelante'),
('Admiral Xtreme'),
('Advanta V12'),
('Agility'),
('AltoSa-SFT'),
('Amphirion Deep'),
('AndraStent XXL'),
('Angio-Seal'),
('AngioBlock'),
('Angioform'),
('Angioguard RX'),
('AngioSculpt'),
('Aperto'),
('Apollo'),
('Approach'),
('Arrow Percutaneous Sheath Introducer'),
('Asahi Chikai black'),
('Asahi Fubuki'),
('Asahi Gaia PV'),
('Asahi Gladius'),
('Asahi Gladius MG PV'),
('Asahi Halberd'),
('Asahi Meister'),
('Asahi SheathLess PV'),
('Asahi Tellus'),
('Asahi Veloute'),
('Astato'),
('Astron'),
('ATW'),
('Auryon'),
('Avanti +'),
('Avigo'),
('AXS Catalyst'),
('AXS Infinity LS'),
('AXS Vecta'),
('Axcess'),
('Babywire'),
('Bearing nsPVA'),
('BeFlared FEVAR'),
('BeFlow iliac'),
('BeGraft'),
('Benchmark'),
('BeSmooth Peripheral'),
('BeYond Venous'),
('BioMimics 3D'),
('BioPath'),
('BMX'),
('Brite Tip'),
('Cantata'),
('Carnelian'),
('Carotid Wallstent'),
('Casper RX'),
('CGuard'),
('Chameleon'),
('Chaperon'),
('Chocolate'),
('ClaudEX'),
('COBRA-OS'),
('Coda'),
('Coated Mandrel Guidewires'),
('Cogent'),
('Conger'),
('Contour'),
('Cougar'),
('Covera'),
('Cronus'),
('Crosperio'),
('Crosstella'),
('Cruiser-18'),
('DABRA'),
('DAC'),
('Destination'),
('Destino'),
('Direxion'),
('Drakon'),
('Drivewire'),
('Dynamic'),
('Dynetic-35'),
('E-Luminexx'),
('E-ventus BX'),
('E-xpand'),
('Easy Flype'),
('Ebony'),
('Echelon'),
('Elite HV'),
('Elutax SV'),
('EmboGold'),
('EmboPro'),
('Emboshield Nav6'),
('Embosphere'),
('Embocure'),
('Embozene'),
('Engage'),
('Enter'),
('Envoy'),
('EOS Guiding Catheter'),
('Epic'),
('Epsylar'),
('Equalizer'),
('ER-REBOA PLUS'),
('Euca PWS'),
('EVAR'),
('EverCross'),
('EverFlex'),
('Excelsior'),
('Exoseal'),
('Express'),
('Extender'),
('Facile'),
('Fathom'),
('FemoSeal'),
('FilterWire EZ'),
('Flexion Guiding Catheter'),
('Flexor'),
('FlowGate2'),
('Fluency Plus'),
('Formula'),
('Fortress'),
('Freeway'),
('Gateway'),
('GliderfleX'),
('Glidewire Gold'),
('Gore DrySeal Flex'),
('Gore Molding & Occlusion Balloon'),
('Gore Viabahn'),
('Gore Viabahn VBX'),
('Gore Viabil'),
('Gore Viatorr'),
('Guider Softip XF'),
('Halo One'),
('HawkOne'),
('Headliner'),
('Headway'),
('HepaSphere'),
('Hi-Torque Command'),
('Hi-Torque Connect'),
('Hi-Torque Proceed'),
('Hi-Torque Winn'),
('Hippocampus'),
('HT Command'),
('HydroPearl'),
('HydroSteer'),
('iCover'),
('Imager II'),
('Impress'),
('In.Pact'),
('Innova'),
('Input'),
('InQwire'),
('Introducer'),
('Intuition'),
('iVolution pro'),
('Jaguar'),
('Jetstream'),
('Jindo'),
('Kitewire Deep'),
('Lantern'),
('Launcher'),
('Legflow'),
('LifePearl'),
('LifeStar'),
('LifeStent'),
('LifeStream'),
('Lotus'),
('Luminor'),
('Lutonix'),
('Mach1'),
('Maestro'),
('MagicTouch'),
('MAK Wires'),
('Mandrel Wires'),
('Manta'),
('Mariner'),
('Marina'),
('Masters Parkway'),
('Mer'),
('Merci Balloon Guide Catheter'),
('Metacross'),
('Microsphere Drug Loadable Beads'),
('MicroStent'),
('Mongoose'),
('Morph'),
('Mozec'),
('Mynx'),
('Myra'),
('NanoCross'),
('Nanoparasol'),
('Nefro C'),
('Neptun C'),
('Neuroscout'),
('Neuro Renegade'),
('Neuron MAX'),
('NeuroSlider'),
('Nitrex'),
('NyloTrack'),
('Oceanus'),
('One Piece Introducer'),
('Optimus'),
('Oscar'),
('Outlook'),
('Pacific'),
('PAK'),
('Palmaz Blue'),
('Palmaz Genesis'),
('Paragon'),
('Passeo'),
('Perclose ProGlide'),
('Perclose ProStyle'),
('Performa'),
('Performer'),
('Peripheral Balloon-Expandable Stent System'),
('Phoenix'),
('pITA'),
('Piton GC'),
('Pointer'),
('pORTAL'),
('Precise Pro RX'),
('Prelude'),
('Prelude Sheath Wire'),
('Pro-Flo'),
('Pro-Kinetic Energy Explorer'),
('Progreat'),
('Prostar XL'),
('ProVia'),
('Prowler'),
('PTA Balloon Catheter'),
('Pulsar-18'),
('Pulsar-35'),
('Pursue'),
('PX Slim'),
('Q50X'),
('QuiremSpheres'),
('Radiant'),
('Radifocus'),
('Radifocus Glidecath'),
('Radifocus Glidewire Advantage'),
('Radifocus Guide Wire'),
('Radifocus Introducer II'),
('Radifocus Optitorque'),
('Ranger'),
('RapidCross'),
('Rapidtransit'),
('Rebar'),
('Reliant'),
('Renegade'),
('Resistant'),
('Restorer'),
('Revive IC'),
('Roadrunner'),
('Roadsaver'),
('Robin'),
('RotarexS'),
('RX Acculink'),
('SafeSheath'),
('Select Catheter'),
('Selution SLR'),
('Senri'),
('Sentrant'),
('SeQuent Please'),
('Sherpa NX'),
('SilverSpeed'),
('Simpass Endo'),
('sinus-Obliquus'),
('sinus-Repo-Visual'),
('sinus-SuperFlex'),
('sinus-Venous'),
('sinus-XL'),
('SiteSeer'),
('SMART Control'),
('SMART Flex'),
('Soft-Vu'),
('Solaris'),
('Specialty Wires'),
('Spex'),
('SpiderFX'),
('Splash'),
('Spring Wire'),
('Stabilizer'),
('StarClose SE'),
('Stealth 360'),
('Stellarex'),
('Storq'),
('Super Arrow-Flex'),
('Super Sheath'),
('Supera'),
('SuperCross'),
('Supertorque'),
('Surefire'),
('SV Wire'),
('SwiftNinja'),
('Synchro'),
('Tearaway Introducer'),
('Tempo'),
('Tentos'),
('Tercross'),
('Torcon NB Advantage'),
('Torx'),
('Transend'),
('Transit'),
('Traxcess'),
('Trevo'),
('Triton'),
('True Form'),
('Tsunami'),
('Tuohy-Borst Introducer'),
('Turbo-Elite'),
('Turnpike'),
('U-Flex'),
('Ultimum'),
('V-14'),
('V-18'),
('Valved Peelable Introducer'),
('Vascade'),
('Velocity'),
('Venovo'),
('Vici'),
('Victory'),
('Visi-Pro'),
('Vista Brite Tip'),
('Wallgraft'),
('Wallstent'),
('Wallstent-Uni'),
('Wedge'),
('Wingman'),
('Wrapsody'),
('X.Act'),
('Z2'),
('Zeus CC'),
('Zeus SX'),
('Zilver'),
('Zilver Vena'),
('Zinger'),
('ZIPwire'),
('Zuma');

-- ============================================
-- Fertig! Die Produktnamen-Vorschläge sind hinzugefügt.
-- Die Backend-Route muss angepasst werden, um beide Tabellen
-- (products UND product_name_suggestions) zu kombinieren.
-- ============================================
